[package]
name = "tiny_wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.11.0"
wgpu = "0.19.3"

[dev-dependencies]
pollster = "0.3.0"
winit = "0.29.15"
bytemuck = "1.15.0"